{
 "title": "GCP Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_ids",
    "label": "project_ids",
    "query": "select distinct(project_id) from gcp_resources"
   },
   {
    "name": "cq_tables",
    "label": "cq_tables",
    "query": "select distinct(cq_table) from gcp_resources"
   }
  ]
 },
 "panels": [
  { "title": "CloudQuery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Source",
   "type": "stat",
   "description": "This panel will show OK if the gcp_resources view has been created and is accessible to the current Postgres user. See https://github.com/cloudquery/dashboards#gcp for more information.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables\n     WHERE  table_schema = 'public'\n     AND    table_name   = 'gcp_resources'"
    }
   ]
  },
  {
   "title": "Last Fetch",
   "type": "stat",
   "description": "Time since the most recent CloudQuery fetch happened.",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select fetch_date as time, 1 from gcp_resources order by fetch_date desc limit 1;"
    }
   ]
  },
  { "title": "Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_resources where project_id in (${project_ids}) and cq_table in (${cq_tables})"
    }
   ]
  },
  {
   "title": "Total Resource by Account",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id as label, count(*) from gcp_resources where cq_table in (${cq_tables}) group by project_id order by count desc"
    }
   ]
  },
  {
   "title": "Resource Type",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 14, "y": 4 },
   "targets": [
    {
     "rawSql": "select cq_table, count(*) from gcp_resources where project_id in (${project_ids}) group by cq_table order by count desc"
    }
   ]
  },
  {
   "title": "All Resources",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select * from gcp_resources where project_id in (${project_ids}) and cq_table in (${cq_tables});"
    }
   ]
  }
 ]
}