{
 "title": "Azure Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "subscription_ids",
    "query": "select distinct(subscription_id) from azure_resources"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(cq_table) from azure_resources;"
   },
   {
    "name": "locations",
    "query": "select distinct(location) from azure_resources;"
   }
  ]
 },
 "panels": [
  { "title": "CloudQuery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Source",
   "type": "stat",
   "description": "This panel will show OK if the aws_resources view has been created and is accessible to the current Postgres user. See https://github.com/cloudquery/dashboards#aws for more information.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables\n     WHERE  table_schema = 'public'\n     AND    table_name   = 'azure_resources'"
    }
   ]
  },
  {
   "title": "Last Fetch",
   "type": "stat",
   "description": "Time since the most recent CloudQuery fetch happened.",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select fetch_date as time, 1 from azure_resources order by fetch_date desc limit 1;"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from azure_resources where subscription_id in (${subscription_ids}) AND location in (${locations}) and cq_table in (${cq_tables});"
    }
   ]
  },
  {
   "title": "Total Resources by Subscription",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select coalesce(azss.display_name, ar.subscription_id) as name, count(*) from azure_resources ar\nleft join azure_subscription_subscriptions azss on azss.subscription_id = ar.subscription_id\nwhere \n  location in (${locations}) \n  and cq_table in (${cq_tables}) \ngroup by coalesce(azss.display_name, ar.subscription_id)\norder by count desc;"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "rawSql": "select cq_table, count(*) \nfrom azure_resources \nwhere subscription_id in (${subscription_ids})\nand cq_table in (${cq_tables}) \nand location in (${locations}) \ngroup by cq_table order by count desc;"
    }
   ]
  },
  {
   "title": "Resource Map",
   "type": "geomap",
   "description": "Excludes resources with no specified location",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select azal.name, latitude::float, longitude::float, count(*) from azure_resources azr\nleft join azure_account_locations azal on azal.name = azr.location\nwhere azr.subscription_id in (${subscription_ids}) \nand azr.location != 'unavailable'\nand cq_table in (${cq_tables}) \ngroup by azal.name, latitude, longitude order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Location",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "select location, count(*) from azure_resources where subscription_id in (${subscription_ids}) and cq_table in (${cq_tables}) group by location order by count desc;"
    }
   ]
  },
  {
   "title": "Azure Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select cq_id, cq_table, subscription_id, location, id, fetch_date from azure_resources \nwhere subscription_id in (${subscription_ids}) \nand location in (${locations})\nand cq_table in (${cq_tables});"
    }
   ]
  }
 ]
}