{
 "title": "VPC Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "VPCs", "label": "VPC", "query": "select  id from aws_ec2_vpcs" },
   {
    "name": "Subnets",
    "label": "Subnet",
    "query": "select id from aws_ec2_subnets where vpc_id in (${VPCs})"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "select region from aws_ec2_vpcs where id in (${VPCs})"
   },
   {
    "name": "route_assoc",
    "label": "route_assoc",
    "query": "select distinct(route_table_cq_id) from aws_ec2_route_table_associations where subnet_id in (${Subnets})"
   },
   {
    "name": "route_table",
    "label": "route_table",
    "query": "select id from aws_ec2_route_tables where cq_id in (${route_assoc})"
   }
  ]
 },
 "panels": [
  {
   "title": "Public Instances",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (Tags->>'Name') as Name,\n  subnet_id,\n  id,\n  region,\n  private_ip_address,\n  public_ip_address\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and aws_ec2_instances.region in (${Region}) and aws_ec2_instances.public_ip_address is not null)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as \"Public Instances\"\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and aws_ec2_instances.region in (${Region}) and aws_ec2_instances.public_ip_address is not null)"
    },
    {
     "rawSql": "SELECT\n  count(*) as \"Private Instances\"\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and aws_ec2_instances.region in (${Region}) and aws_ec2_instances.public_ip_address is null)"
    }
   ]
  },
  {
   "title": "Private Instances",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  (Tags->>'Name') as Name,\n  subnet_id,\n  id,\n  region,\n  private_ip_address\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and region in (${Region}) and aws_ec2_instances.public_ip_address is null)"
    }
   ]
  },
  {
   "title": "Active Routing Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select distinct aws_ec2_route_table_routes.destination_cidr_block as destination, aws_ec2_route_table_routes.gateway_id, aws_ec2_route_table_routes.instance_id,aws_ec2_route_table_routes.nat_gateway_id, aws_ec2_route_table_routes.state from aws_ec2_route_table_routes where aws_ec2_route_table_routes.route_table_cq_id in (${route_assoc})"
    }
   ]
  }
 ]
}