{
 "title": "AWS Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_ids",
    "query": "select distinct(account_id) from aws_resources"
   },
   {
    "name": "regions",
    "query": "select distinct(region) from aws_resources;"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(cq_table) from aws_resources;"
   }
  ]
 },
 "panels": [
  { "title": "CloudQuery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Source",
   "type": "stat",
   "description": "This panel will show OK if the aws_resources view has been created and is accessible to the current Postgres user. See https://github.com/cloudquery/dashboards#aws for more information.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables\n     WHERE  table_schema = 'public'\n     AND    table_name   = 'aws_resources'"
    }
   ]
  },
  {
   "title": "Last Fetch",
   "type": "stat",
   "description": "Time since the most recent CloudQuery fetch happened.",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select fetch_date as time, 1 from aws_resources order by fetch_date desc limit 1;"
    }
   ]
  },
  { "title": "AWS Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_resources where account_id in (${account_ids}) AND region in (${regions}) and cq_table in (${cq_tables});"
    }
   ]
  },
  {
   "title": "Total Resource by Account",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_resources where region in (${regions}) and cq_table in (${cq_tables}) group by account_id order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_resources where account_id in (${account_ids}) group by region order by count desc;"
    }
   ]
  },
  {
   "title": "AWS Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select cq_id, cq_table, account_id, region, arn, fetch_date from aws_resources where account_id in (${account_ids}) and region in (${regions}) and cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select cq_table, count(*) from aws_resources where account_id in (${account_ids}) and region in (${regions}) group by cq_table order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 25 },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_resources where account_id in (${account_ids}) group by region order by count desc;"
    }
   ]
  }
 ]
}